// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4UCaHhpLsGfYBjGQoOH9fe_AMJHtULhc',
    appId: '1:517599876597:web:a080a9114dce6431643cbc',
    messagingSenderId: '517599876597',
    projectId: 'babyshophub01-72066',
    authDomain: 'babyshophub01-72066.firebaseapp.com',
    storageBucket: 'babyshophub01-72066.firebasestorage.app',
    measurementId: 'G-CE1XDCD3G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBf7QvAaPQ6vKpo7AaqQE6Xlgdl2FmkOw',
    appId: '1:517599876597:android:f4f344ed2786cd73643cbc',
    messagingSenderId: '517599876597',
    projectId: 'babyshophub01-72066',
    storageBucket: 'babyshophub01-72066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqf3xUDTJSgBTu228orGAbE6Gyf-niNS8',
    appId: '1:517599876597:ios:00b1c55317ef7760643cbc',
    messagingSenderId: '517599876597',
    projectId: 'babyshophub01-72066',
    storageBucket: 'babyshophub01-72066.firebasestorage.app',
    iosBundleId: 'com.example.mystore',
  );
}
